# Pandas Library

In [1]:
#!pip install pandas

In [2]:
import pandas as pd

In [4]:
#series

s = pd.Series([10,20,30,40], index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
#Data frame

data = {
    "name":["ali","ayse","mehmet"],
    "age":[25,30,22],
    "city":["Ankara","İstanbul","İzmir"]
}

df = pd.DataFrame(data)
df

     name  age      city
0     ali   25    Ankara
1    ayse   30  İstanbul
2  mehmet   22     İzmir

In [9]:
print(f"Shape (row, column): {df.shape}")
print(f"Column names: {df.columns}")
print(f"Row indexes: {df.index}")
print(f"Data type: \n {df.dtypes}")

Shape (row, column): (3, 3)
Column names: Index(['name', 'age', 'city'], dtype='object')
Row indexes: RangeIndex(start=0, stop=3, step=1)
Data type:
 name    object
age      int64
city    object
dtype: object

##Pandas Series

In [11]:
#Creating series

import pandas as pd

s1 = pd.Series([10,20,30,40]) #create series from list
s1

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
s2 = pd.Series([10,20,30,40], index = ["a","b","c","d"])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [14]:
#create seried from dictionary

data = {"Ali":55, "Ayse":45,"Mehmet":25}
s3 = pd.Series(data)
s3

Ali       55
Ayse      45
Mehmet    25
dtype: int64

In [16]:
# Basic Features

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [17]:
print(f"Values: {s.values}")
print(f"Indexes: {s.index}")
print(f"Data type: {s.dtype}")
print(f"Shape: {s.shape}")

Values: [10 20 30 40]
Indexes: Index(['a', 'b', 'c', 'd'], dtype='object')
Data type: int64
Shape: (4,)

In [18]:
# Indexing and Slicing

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [19]:
s["b"] #single element access

np.int64(20)

In [20]:
s["a":"c"] #slicing

a    10
b    20
c    30
dtype: int64

In [21]:
s[0:2] #access with numerical index

a    10
b    20
dtype: int64

In [23]:
#functions on series

print(f"Sum: {s.sum()}")
print(f"Mean: {s.mean()}")
print(f"Std: {s.std()}")
print(f"Max: {s.max()}")
print(f"Min: {s.min()}")

Sum: 100
Mean: 25.0
Std: 12.909944487358056
Max: 40
Min: 10

In [24]:
# unique values

s = pd.Series([10,20,30,30,30,50,50])
s.unique()

array([10, 20, 30, 50])

In [25]:
#the number of each unique value
s.value_counts()

30    3
50    2
20    1
10    1
Name: count, dtype: int64

## Pandas DataFrames

In [39]:
#creating with dictionaries

import pandas as pd

data = {
    "name":["Ali","Ayse","Mehmet"],
    "age":[25,30,22],
    "city":["Ankara","İstanbul","İzmir"]
}

data

{'name': ['Ali', 'Ayse', 'Mehmet'],
 'age': [25, 30, 22],
 'city': ['Ankara', 'İstanbul', 'İzmir']}

In [40]:
df = pd.DataFrame(data)
df

     name  age      city
0     Ali   25    Ankara
1    Ayse   30  İstanbul
2  Mehmet   22     İzmir

In [29]:
#creat with numpy array

import numpy as np

arr = np.array([[1, "Ali", 25],
                [2, "Ayşe", 30],
                [3,"Mehmet", 22]])

In [30]:
df2 = pd.DataFrame(arr, columns=["id","name","age"])
df2

  id    name age
0  1     Ali  25
1  2    Ayşe  30
2  3  Mehmet  22

In [31]:
print(f"Shape (row, column): {df2.shape}")
print(f"Column names: {df2.columns}")
print(f"Row indexes: {df2.index}")
print(f"Data type: \n {df2.dtypes}")

Shape (row, column): (3, 3)
Column names: Index(['id', 'name', 'age'], dtype='object')
Row indexes: RangeIndex(start=0, stop=3, step=1)
Data type:
 id      object
name    object
age     object
dtype: object

In [32]:
# row and column selections

#iloc, loc, indexing

print(df["age"]) #select one column
print(df.loc[:,"age"])

0    25
1    30
2    22
Name: age, dtype: int64
0    25
1    30
2    22
Name: age, dtype: int64

In [34]:
print(df[["name","age"]]) #select multiple columns
print(df.loc[:, ["name","age"]])

     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22
     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22

In [35]:
# add and delete column

df["mark"] = [80,90,85]
df

     name  age      city  mark
0     Ali   25    Ankara    80
1    Ayse   30  İstanbul    90
2  Mehmet   22     İzmir    85

In [41]:
df.drop("city", axis=1, inplace = True) # axis = 1 -> delete column
df

     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22