<a href="https://colab.research.google.com/github/sevdeaslanturkiyeli/AI_Development_Bootcamp/blob/main/02_pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Library

In [1]:
#!pip install pandas

In [2]:
import pandas as pd

In [4]:
#series

s = pd.Series([10,20,30,40], index=['a','b','c','d'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
#Data frame

data = {
    "name":["ali","ayse","mehmet"],
    "age":[25,30,22],
    "city":["Ankara","İstanbul","İzmir"]
}

df = pd.DataFrame(data)
df

     name  age      city
0     ali   25    Ankara
1    ayse   30  İstanbul
2  mehmet   22     İzmir

In [9]:
print(f"Shape (row, column): {df.shape}")
print(f"Column names: {df.columns}")
print(f"Row indexes: {df.index}")
print(f"Data type: \n {df.dtypes}")

Shape (row, column): (3, 3)
Column names: Index(['name', 'age', 'city'], dtype='object')
Row indexes: RangeIndex(start=0, stop=3, step=1)
Data type:
 name    object
age      int64
city    object
dtype: object

##Pandas Series

In [11]:
#Creating series

import pandas as pd

s1 = pd.Series([10,20,30,40]) #create series from list
s1

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
s2 = pd.Series([10,20,30,40], index = ["a","b","c","d"])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [14]:
#create seried from dictionary

data = {"Ali":55, "Ayse":45,"Mehmet":25}
s3 = pd.Series(data)
s3

Ali       55
Ayse      45
Mehmet    25
dtype: int64

In [16]:
# Basic Features

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [17]:
print(f"Values: {s.values}")
print(f"Indexes: {s.index}")
print(f"Data type: {s.dtype}")
print(f"Shape: {s.shape}")

Values: [10 20 30 40]
Indexes: Index(['a', 'b', 'c', 'd'], dtype='object')
Data type: int64
Shape: (4,)

In [18]:
# Indexing and Slicing

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [19]:
s["b"] #single element access

np.int64(20)

In [20]:
s["a":"c"] #slicing

a    10
b    20
c    30
dtype: int64

In [21]:
s[0:2] #access with numerical index

a    10
b    20
dtype: int64

In [23]:
#functions on series

print(f"Sum: {s.sum()}")
print(f"Mean: {s.mean()}")
print(f"Std: {s.std()}")
print(f"Max: {s.max()}")
print(f"Min: {s.min()}")

Sum: 100
Mean: 25.0
Std: 12.909944487358056
Max: 40
Min: 10

In [24]:
# unique values

s = pd.Series([10,20,30,30,30,50,50])
s.unique()

array([10, 20, 30, 50])

In [25]:
#the number of each unique value
s.value_counts()

30    3
50    2
20    1
10    1
Name: count, dtype: int64

## Pandas DataFrames

In [39]:
#creating with dictionaries

import pandas as pd

data = {
    "name":["Ali","Ayse","Mehmet"],
    "age":[25,30,22],
    "city":["Ankara","İstanbul","İzmir"]
}

data

{'name': ['Ali', 'Ayse', 'Mehmet'],
 'age': [25, 30, 22],
 'city': ['Ankara', 'İstanbul', 'İzmir']}

In [40]:
df = pd.DataFrame(data)
df

     name  age      city
0     Ali   25    Ankara
1    Ayse   30  İstanbul
2  Mehmet   22     İzmir

In [29]:
#creat with numpy array

import numpy as np

arr = np.array([[1, "Ali", 25],
                [2, "Ayşe", 30],
                [3,"Mehmet", 22]])

In [30]:
df2 = pd.DataFrame(arr, columns=["id","name","age"])
df2

  id    name age
0  1     Ali  25
1  2    Ayşe  30
2  3  Mehmet  22

In [31]:
print(f"Shape (row, column): {df2.shape}")
print(f"Column names: {df2.columns}")
print(f"Row indexes: {df2.index}")
print(f"Data type: \n {df2.dtypes}")

Shape (row, column): (3, 3)
Column names: Index(['id', 'name', 'age'], dtype='object')
Row indexes: RangeIndex(start=0, stop=3, step=1)
Data type:
 id      object
name    object
age     object
dtype: object

In [32]:
# row and column selections

#iloc, loc, indexing

print(df["age"]) #select one column
print(df.loc[:,"age"])

0    25
1    30
2    22
Name: age, dtype: int64
0    25
1    30
2    22
Name: age, dtype: int64

In [34]:
print(df[["name","age"]]) #select multiple columns
print(df.loc[:, ["name","age"]])

     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22
     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22

In [35]:
# add and delete column

df["mark"] = [80,90,85]
df

     name  age      city  mark
0     Ali   25    Ankara    80
1    Ayse   30  İstanbul    90
2  Mehmet   22     İzmir    85

In [41]:
df.drop("city", axis=1, inplace = True) # axis = 1 -> delete column
df

     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   22

##Saving and Reading Data

In [44]:
import pandas as pd

data = {
    "name":["Ali","Ayşe","Mehmet","Zeynep","Burak","Elif","Can","Deniz","Merve","Mert"],
    "age":[20,21,19,22,20,23,24,21,22,20],
    "mark":[85,40,72,95,60,55,100,45,70,65]
}
df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60
5    Elif   23    55
6     Can   24   100
7   Deniz   21    45
8   Merve   22    70
9    Mert   20    65

In [45]:
#save
df.to_csv("students.csv",index= False)
df.to_excel("students.xlsx",index= False)
df.to_json("students.json",orient ="records", lines = True)

In [46]:
#read
df_csv = pd.read_csv("students.csv")
df_csv

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60
5    Elif   23    55
6     Can   24   100
7   Deniz   21    45
8   Merve   22    70
9    Mert   20    65

In [47]:
df_excel = pd.read_excel("students.xlsx")
df_excel

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60
5    Elif   23    55
6     Can   24   100
7   Deniz   21    45
8   Merve   22    70
9    Mert   20    65

In [48]:
df_json = pd.read_json("students.json",lines = True)
df_json

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60
5    Elif   23    55
6     Can   24   100
7   Deniz   21    45
8   Merve   22    70
9    Mert   20    65

## Data Review and Summarization

In [49]:
#first and last lines

import pandas as pd

data = {
    "name":["Ali","Ayşe","Mehmet","Zeynep","Burak"],
    "age":[20,21,19,22,20],
    "mark":[85,40,72,95,60]
}

df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [51]:
df.head()

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [52]:
df.tail()

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [53]:
df.shape

(5, 3)

In [54]:
df.columns

Index(['name', 'age', 'mark'], dtype='object')

In [55]:
df.dtypes

name    object
age      int64
mark     int64
dtype: object

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   mark    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [57]:
# basic statistical analyze
df.describe()

             age       mark
count   5.000000   5.000000
mean   20.400000  70.400000
std     1.140175  21.524405
min    19.000000  40.000000
25%    20.000000  60.000000
50%    20.000000  72.000000
75%    21.000000  85.000000
max    22.000000  95.000000

In [58]:
df.isnull()

    name    age   mark
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [59]:
df.isnull().sum()

name    0
age     0
mark    0
dtype: int64

In [61]:
df.loc[2, "mark"] = None
df

     name  age  mark
0     Ali   20  85.0
1    Ayşe   21  40.0
2  Mehmet   19   NaN
3  Zeynep   22  95.0
4   Burak   20  60.0

In [62]:
print(df.isnull())
print(df.isnull().sum())

    name    age   mark
0  False  False  False
1  False  False  False
2  False  False   True
3  False  False  False
4  False  False  False
name    0
age     0
mark    1
dtype: int64

In [63]:
#unique values

df["age"].unique()

array([20, 21, 19, 22])

In [64]:
#How many different ages ?

df["age"].nunique()

4

In [65]:
df.value_counts()

name    age  mark
Ali     20   85.0    1
Ayşe    21   40.0    1
Burak   20   60.0    1
Zeynep  22   95.0    1
Name: count, dtype: int64

In [66]:
df["age"].value_counts()

age
20    2
21    1
19    1
22    1
Name: count, dtype: int64

## Data selection and filtering

In [68]:

import pandas as pd

data = {
    "name":["Ali","Ayşe","Mehmet","Zeynep","Burak"],
    "age":[20,21,19,22,20],
    "mark":[85,40,72,95,60]
}

df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [69]:
#conditional filtering

print(f"Mark > 70 : \n {df[df["mark"]>70]}")

Mark > 70 :
      name  age  mark
0     Ali   20    85
2  Mehmet   19    72
3  Zeynep   22    95

In [70]:
print(f"Age = 20 \n {df[df["age"]==20]}")

Age = 20
     name  age  mark
0    Ali   20    85
4  Burak   20    60

In [71]:
#boolean masks

mask = df["mark"] >= 60
mask

0     True
1    False
2     True
3     True
4     True
Name: mark, dtype: bool

In [72]:
df[mask]

     name  age  mark
0     Ali   20    85
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [73]:
#multiple conditions

# 50<= mark <= 90

print(f"Average success : {df[(df["mark"] >= 50) & (df["mark"] <= 90 )]}")

Average success :      name  age  mark
0     Ali   20    85
2  Mehmet   19    72
4   Burak   20    60

## Data Cleaning

In [74]:
import pandas as pd

data = {
    "name":["Ali","Ayşe","Mehmet","Zeynep","Burak"],
    "age":[20,None,19,22,None],
    "mark":[85,40,None,95,60]
}

df = pd.DataFrame(data)
df

     name   age  mark
0     Ali  20.0  85.0
1    Ayşe   NaN  40.0
2  Mehmet  19.0   NaN
3  Zeynep  22.0  95.0
4   Burak   NaN  60.0

In [75]:
df.isnull()

    name    age   mark
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [77]:
df.isnull().sum()

name    0
age     2
mark    1
dtype: int64

In [78]:
df.dropna() #delete

     name   age  mark
0     Ali  20.0  85.0
3  Zeynep  22.0  95.0

In [80]:
df.fillna(0) #fill in missing data

     name   age  mark
0     Ali  20.0  85.0
1    Ayşe   0.0  40.0
2  Mehmet  19.0   0.0
3  Zeynep  22.0  95.0
4   Burak   0.0  60.0

In [81]:
df["age"].fillna(df["age"].mean())

0    20.000000
1    20.333333
2    19.000000
3    22.000000
4    20.333333
Name: age, dtype: float64

In [84]:

data = {
    "name":["Ali","Ayşe","Ali","Zeynep","Burak"],
    "age":[20,21,20,22,22],
    "mark":[85,40,85,95,60]
}

df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2     Ali   20    85
3  Zeynep   22    95
4   Burak   22    60

In [85]:
#duplicate data
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [86]:
df.drop_duplicates()

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
3  Zeynep   22    95
4   Burak   22    60

In [88]:
#change value

df.replace({"Ali":"Ali_isim"})

       name  age  mark
0  Ali_isim   20    85
1      Ayşe   21    40
2  Ali_isim   20    85
3    Zeynep   22    95
4     Burak   22    60

In [89]:
data = {
    "name":[" Ali","Ayşe","Ali","ZeYnep","Burak"],
    "age":[20,21,20,22,22],
    "mark":[85,40,85,95,60]
}

df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2     Ali   20    85
3  ZeYnep   22    95
4   Burak   22    60

In [90]:
#string operations

df["name"] = df["name"].str.lower()
df

     name  age  mark
0     ali   20    85
1    ayşe   21    40
2     ali   20    85
3  zeynep   22    95
4   burak   22    60

In [91]:
df["name"] = df["name"].str.strip()
df

     name  age  mark
0     ali   20    85
1    ayşe   21    40
2     ali   20    85
3  zeynep   22    95
4   burak   22    60

## Data Conversion

In [92]:
data = {
    "name":["Ali","Ayşe","Mehmet","Zeynep","Burak"],
    "age":[20,21,19,22,20],
    "mark":[85,40,72,95,60]
}

df = pd.DataFrame(data)
df

     name  age  mark
0     Ali   20    85
1    Ayşe   21    40
2  Mehmet   19    72
3  Zeynep   22    95
4   Burak   20    60

In [94]:
#sorting

df.sort_values(by = "mark", ascending=False)

     name  age  mark
3  Zeynep   22    95
0     Ali   20    85
2  Mehmet   19    72
4   Burak   20    60
1    Ayşe   21    40

In [98]:
#reindexing
df = df.reindex([1,4,2,0,3])
df

     name  age  mark
1    Ayşe   21    40
4   Burak   20    60
2  Mehmet   19    72
0     Ali   20    85
3  Zeynep   22    95

In [99]:
#type conversion
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   mark    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 160.0+ bytes

In [100]:
df["mark"] = df["mark"].astype(float)
df

     name  age  mark
1    Ayşe   21  40.0
4   Burak   20  60.0
2  Mehmet   19  72.0
0     Ali   20  85.0
3  Zeynep   22  95.0

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   mark    5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

In [102]:
#add categorical data

df["city"] = ["ankara","izmir","antalya","konya","istanbul"]
df

     name  age  mark      city
1    Ayşe   21  40.0    ankara
4   Burak   20  60.0     izmir
2  Mehmet   19  72.0   antalya
0     Ali   20  85.0     konya
3  Zeynep   22  95.0  istanbul

In [103]:
df["city"] = df["city"].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 1 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   mark    5 non-null      float64
 3   city    5 non-null      category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 377.0+ bytes

## Grouping and Summarizing

In [110]:
#Basic grouping

import pandas as pd

data = {
    "department": ["IT","IT","HR","HR","Accounting","IT"],
    "employee": ["ali","ayşe","mehmet","zeynep","burak","can"],
    "salary":[5000,6000,4000,4500,7000,5500]
}

df = pd.DataFrame(data)
df

   department employee  salary
0          IT      ali    5000
1          IT     ayşe    6000
2          HR   mehmet    4000
3          HR   zeynep    4500
4  Accounting    burak    7000
5          IT      can    5500

In [105]:
#Grouping by department and average salary

df.groupby("department")["salary"].mean()

department
Accounting    7000.0
HR            4250.0
IT            5500.0
Name: salary, dtype: float64

In [106]:
# total , averaging, and counting

df.groupby("department")["salary"].sum() #total

department
Accounting     7000
HR             8500
IT            16500
Name: salary, dtype: int64

In [108]:
df.groupby("department")["salary"].count() #employee count

department
Accounting    1
HR            2
IT            3
Name: salary, dtype: int64

In [109]:
#min-max
print(df.groupby("department")["salary"].max()) #max salary
print(df.groupby("department")["salary"].min()) #min salary

department
Accounting    7000
HR            4500
IT            6000
Name: salary, dtype: int64
department
Accounting    7000
HR            4000
IT            5000
Name: salary, dtype: int64

In [113]:
#grouping by multiple columns

data = {
    "department": ["IT","IT","HR","HR","Accounting","IT","HR"],
    "city": ["Ankara","İstanbul","İzmir","Ankara","İstanbul","Ankara","İzmir"],
    "salary":[5000,6000,4000,4500,7000,5500,4700]
}

df = pd.DataFrame(data)
df

   department      city  salary
0          IT    Ankara    5000
1          IT  İstanbul    6000
2          HR     İzmir    4000
3          HR    Ankara    4500
4  Accounting  İstanbul    7000
5          IT    Ankara    5500
6          HR     İzmir    4700

In [117]:
df.groupby(["department","city"])["salary"].mean()

department  city
Accounting  İstanbul    7000.0
HR          Ankara      4500.0
            İzmir       4350.0
IT          Ankara      5250.0
            İstanbul    6000.0
Name: salary, dtype: float64

In [118]:
# agg()

df.groupby("department")["salary"].agg(["mean","max","min","count"])

              mean   max   min  count
department
Accounting  7000.0  7000  7000      1
HR          4400.0  4700  4000      3
IT          5500.0  6000  5000      3

## combining and bringing together

In [120]:
#concat

import pandas as pd

df1 = pd.DataFrame({"id":[1,2,3], "name":["Ali","Ayşe","Mehmet"]})
df2 = pd.DataFrame({"id":[4,5,6], "name":["Zeynep","Burak","Elif"]})

In [121]:
#add on top of each other

df_concat = pd.concat([df1,df2])
df_concat

   id    name
0   1     Ali
1   2    Ayşe
2   3  Mehmet
0   4  Zeynep
1   5   Burak
2   6    Elif

In [122]:
#add side by side

df_concat = pd.concat([df1,df2], axis = 1)
df_concat

   id    name  id    name
0   1     Ali   4  Zeynep
1   2    Ayşe   5   Burak
2   3  Mehmet   6    Elif

In [124]:
# merge
df1 = pd.DataFrame({"id":[1,2,3], "name":["Ali","Ayşe","Mehmet"]})
df2 = pd.DataFrame({"id":[1,2,4], "city":["Ankara","İstanbul","İzmir"]})

print("df1: \n", df1)
print("\n df2:\n",df2)

df1:
    id    name
0   1     Ali
1   2    Ayşe
2   3  Mehmet

 df2:
    id      city
0   1    Ankara
1   2  İstanbul
2   4     İzmir

In [125]:
df_merge = pd.merge(df1, df2, on = "id", how="inner")
df_merge

   id  name      city
0   1   Ali    Ankara
1   2  Ayşe  İstanbul

In [126]:
df_merge = pd.merge(df1, df2, on = "id", how="left")
df_merge

   id    name      city
0   1     Ali    Ankara
1   2    Ayşe  İstanbul
2   3  Mehmet       NaN

In [127]:
df_merge = pd.merge(df1, df2, on = "id", how="right")
df_merge

   id  name      city
0   1   Ali    Ankara
1   2  Ayşe  İstanbul
2   4   NaN     İzmir

In [128]:
# index based join

df1 = pd.DataFrame({"name":["Ali","Ayşe","Mehmet"]}, index=["a","b","c"])
df2 = pd.DataFrame({"mark":[85,90,75]}, index=["a","b","d"])


print("df1: \n", df1)
print("\n df2:\n",df2)

df1:
      name
a     Ali
b    Ayşe
c  Mehmet

 df2:
    mark
a    85
b    90
d    75

In [130]:
pd.merge(df1,df2, left_index = True, right_index=True, how="outer") #all values

     name  mark
a     Ali  85.0
b    Ayşe  90.0
c  Mehmet   NaN
d     NaN  75.0